version: '3'                                              
services:                                                 
  redis:                                                  
    container_name: "jp_star_redis"                               
    image: "redis"                                        
    command: ["redis-server", "--requirepass", "foobared"]
    ports:                                                
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: jp_elasticsearch
    environment:
      - cluster.name=docker-cluster
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: "jp_kibana"
    image: "docker.elastic.co/kibana/kibana:6.3.0"
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:docker-cluster"
              
