version: '3'                                              
services:                                                 
  redis:                                                  
    container_name: "jp_star_redis"                               
    image: "redis"                                        
    command: ["redis-server", "--requirepass", "foobared"]
    ports:                                                
      - "6379:6379"                 
